wireplumber.components.args = {
  "monitor.raop.rules" = [
    {
      matches = [
        { node.name = "~raop_sink\\.HomePod.*" }
      ]
      apply_properties = {
        node.pause-on-idle          = false
        session.suspend-timeout-seconds = 0
      }
    }
  ]
}
