monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.usb-Sony_Interactive_Entertainment_Wireless_Controller-00.HiFi__Speaker__sink"
      }
    ]
    actions = {
      update-props = {
        node.description = "Dualsense"
      }
    }
  }
]
